<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<div class="container">
	<div class="wrap-header wrapp-header">
		<div class="right-column left-side">
			<div class="mobile-nav-icon">
				<span class="basel-burger"></span>
			</div>
			
		</div>
		<div class="site-logo">
			<div class="basel-logo-wrap">
				<a href="http://dev.furybros.com/" class="basel-logo basel-main-logo" rel="home">
					<img src="http://dev.furybros.com/wp-content/uploads/Fury-Bros-Logo-Final.svg" alt="Fury Bros.">
				</a>
			</div>
		</div>
		<div class="main-nav site-navigation basel-navigation menu-left" role="navigation">
			<div class="menu-main-menu-container">
				<ul id="menu-main-menu-1" class="menu">
					<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1316 menu-item-design-default item-event-hover">
						<a href="/store">Shop</a>
						<div class="sub-menu-dropdown color-scheme-dark" style="">
							<div class="container">
								<ul class="sub-menu color-scheme-dark">
									<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1318 menu-item-design-default item-event-hover"><a href="/store/index.php/candles.html">Candles</a></li>
									<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1319 menu-item-design-default item-event-hover"><a href="/store/index.php/soaps.html">Soaps</a></li>
									<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1320 menu-item-design-default item-event-hover"><a href="/store/index.php/solid-cologne.html">Solid Cologne</a></li>
									<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1321 menu-item-design-default item-event-hover"><a href="/store/index.php/accessories.html">Accessories</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1508 menu-item-design-default item-event-hover" style="margin-right: 316px;">
						<a href="http://dev.furybros.com/contact/">Contact Us</a>
						<div class="sub-menu-dropdown color-scheme-dark" style="">
							<div class="container">
								<ul class="sub-menu color-scheme-dark">
									<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1509 menu-item-design-default item-event-hover"><a href="http://dev.furybros.com/contact/">Contact Us</a></li>
									<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1572 menu-item-design-default item-event-hover"><a href="/store/index.php/customer/account/login/">Wholesale Login</a></li>
									<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-799 menu-item-design-default item-event-hover"><a href="http://dev.furybros.com/wholesale-policy/">Wholesale Policy</a></li>
									<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-805 menu-item-design-default item-event-hover"><a href="http://dev.furybros.com/digital-catalog/">Digital Catalog</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1406 menu-item-design-default item-event-hover">
						<a href="/about-fury-bros/">About</a>
					</li>
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-480 menu-item-design-default item-event-hover" style="margin-right: 13px;">
						<a href="http://dev.furybros.com/retail-locations/">Retailers</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="right-column">
			<div class="header-links">
			</div>
		</div>
	</div>
</div>
