<div class="topbar-wrapp color-scheme-light">
			<div class="container">
				<div class="topbar-content">
					<div class="top-bar-left">
						
													<a href="/store/index.php/customer/account/login/">SIGN IN</a> | <a href="/store/index.php/customer/account/create/">CREATE AN ACCOUNT</a> | <a href="/store/index.php/checkout/cart/">VIEW CART</a>												
						
					</div>
					<div class="top-bar-right">
						<div class="topbar-menu">
							<div class="menu-top-bar-container"><ul id="menu-top-bar" class="menu"><li id="menu-item-1310" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1310 menu-item-design-default item-event-hover"><a href="https://www.facebook.com/furybros/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
<li id="menu-item-1312" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1312 menu-item-design-default item-event-hover"><a href="https://www.instagram.com/furybros/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
<li id="menu-item-1313" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1313 menu-item-design-default item-event-hover"><a href="mailto:info@furybros.com"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
</ul></div>						</div>
					</div>
				</div>
			</div>
		</div>