<div class="mobile-nav">
    <div class="menu-main-menu-container">
        <ul id="menu-main-menu" class="site-mobile-menu">
            <li id="menu-item-1316" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1316 menu-item-design-default item-event-hover"><a href="/store/index.php/candles.html">Shop</a>
            </li>
            <li id="menu-item-1508" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1508 menu-item-design-default item-event-hover"><a href="/contact/">Contact Us</a>
            </li>
            <li id="menu-item-1406" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1406 menu-item-design-default item-event-hover"><a href="/about-fury-bros/">About</a></li>
            <li id="menu-item-480" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-480 menu-item-design-default item-event-hover"><a href="/retail-locations/">Retailers</a></li>
        </ul>
    </div>
</div>
